import { ShaderMaterial } from "three";
import * as THREE from "three";

export default class extends ShaderMaterial {
    constructor() {
        super({
            uniforms: {
                iTime: { value: 10 },
                iResolution: { value: new THREE.Vector3() }
            },
            vertexShader: `
                void main() {
                    gl_Position = vec4(position.xy, 0.0, 1.0);
                }
            `,
            fragmentShader: `
                uniform float iTime;
                uniform vec3 iResolution;

                #define PI 3.141592
                #define TWOPI (2.0*PI)

                vec3 palette( float t ) {
                    vec3 a = vec3(0.5, 0.6, 0.5);
                    vec3 b = vec3(0.5, 0.5, 0.85);
                    vec3 c = vec3(1.0, 1.0, 1.0);
                    vec3 d = vec3(0.756,0.48,0.557);

                    return a + b*cos( TWOPI*(c*t+d) );
                }
                // Full-Screen Molten Goo
                // Lava-like full-screen dynamic blob field
                // Generated by ChatGPT 4o on July 27, 2025

                float hash(vec2 p) {
                    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
                }

                float noise(vec2 p) {
                    vec2 i = floor(p);
                    vec2 f = fract(p);
                    vec2 u = f*f*(3.0 - 2.0*f);
                    return mix(mix(hash(i + vec2(0.0, 0.0)), hash(i + vec2(1.0, 0.0)), u.x),
                               mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), u.x), u.y);
                }

                float fbm(vec2 p) {
                    float v = 0.0;
                    float a = 0.5;
                    for (int i = 0; i < 5; i++) {
                        v += a * noise(p);
                        p *= 2.0;
                        a *= 0.5;
                    }
                    return v;
                }

                #define S(v) smoothstep(5.0 / iResolution.y, 0.0, v)           // AA draw
                  float happy_star(vec2 uv, float anim)
                {
                    uv = abs(uv);
                    vec2 pos = min(uv.xy/uv.yx, anim);
                    float p = (2.0 - pos.x - pos.y);
                    return (2.0+p*(p*p-1.5)) / (uv.x+uv.y);      
                }
                 
                vec3 lavaPalette(float t) {
                    vec3 dark = vec3(0.078, 0.004, 0.004);    // #140101
                    vec3 mid  = vec3(0.8, 0.3, 0.0);          // orange (corrected from 1.0 assuming typo)
                    vec3 bright = vec3(0.996, 0.859, 0.553);  // #FEDB8D

                    if (t < 0.5)
                        return mix(dark, mid, t * 2.0);
                    else
                        return mix(mid, bright, (t - 0.5) * 2.0);
                }

                void mainImage( out vec4 fragColor, in vec2 fragCoord ) {
                    vec2 r = iResolution.xy;
                    vec2 uv = (2.0 * fragCoord - r) / min(r.x, r.y);
                    uv=normalize(vec3(uv,0.3)).xy;
                    vec2 uv0 = uv;
                      float time = iTime * 0.4;
                 vec2 uv2 = ( fragCoord - .5*iResolution.xy ) / iResolution.y;
                 
                 vec4 O=fragColor;
                 vec2 u =fragCoord;

                  vec2 R = iResolution.xy, L,
                         U = fract( 3.*( u - .5*R ) / R.y ) -.5 ;
                       U*=mat2(cos(iTime),sin(iTime),-sin(iTime),cos(iTime));
                      vec2 V = abs( vec2( U.x+U.y, U.x-U.y ) );
                       V*=mat2(cos(iTime),sin(iTime),-sin(iTime),cos(iTime));
                       // 45° rotation and 4-symmetry
                         V = abs( U + vec2( U.y, -U ) );            // 
                    V = V.x > V.y ? V.yx : V;                       // X-Y symmetry
                    
                    L = 1.- S (abs( fract(V*8.+.5) -.5 ) / 8. );    // for thin black lines
                    
                    O =  vec4(    S( V.x-.25 )                      // large white cross
                               *  L.x                               // long thin black lines
                               *( V.y < .27 ? L.y : 1. )            // short thin black lines (square grid)
                               *  S(max(U.x,U.y) - .49 )            // main tiles border
                             );
                 
                 
                    vec2 p = uv * 12.0;

                    // Warp the field over time
                    vec2 offset = vec2(
                        fbm(p + vec2(0.0, time)),
                        fbm(p + vec2(5.2, time + 1.3))
                    );
                    p += offset * 1.2;

                    float field = fbm(p + time * 0.3);

                    // Sharpen features into blobs
                    float intensity = smoothstep(0.3, 0.7, field);

                    // Final color mapping
                    vec3 col2 = lavaPalette(intensity);
                    vec3 finalCol = vec3(0.0);
                    
                    for (int i = 0; i < 4; i++) {
                        uv = fract(uv * 2.257) - 0.5;
                    
                        float d = length(uv) * exp(-length(uv0)) * exp(length(uv));
                    
                        vec3 col = palette(length(uv0) + float(i)*.9 + iTime*.5)+O.xyz;
                    
                        d = sin(d*8. + iTime)/8.;
                        d = abs(d);
                    
                        d = pow(0.0089 / d, PI / 2.0);
                    
                    
                        finalCol += d * col*col2-O.xyz;
                    }

                    fragColor = vec4(finalCol, 1.0);
                    uv *= 2.0 * ( cos(iTime * 2.0) -2.5); // scale
                    float anim = sin(iTime * 12.0) * 0.1 + 1.0;  // anim between 0.9 - 1.1 
                    fragColor*= vec4(happy_star(uv2, anim) * vec3(0.35,0.2,0.15)*2., 1.0);
                    
                }

                void main() {
                    mainImage(gl_FragColor, gl_FragCoord.xy);
                }
            `,
            transparent: false,
            side: THREE.DoubleSide
        });
    }
}
